# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number
    gym(
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.Tissatech.FastAutomate": "c24b0df2-707e-41f4-ab72-bfe79392116a.mobileprovision"
        }
      }
    )
    pilot
    #increment_build_number(xcodeproj: "FastAutomate.xcodeproj")
    #build_app(scheme: "FastAutomate")
    #upload_to_testflight
  end
end
